### ISSUE TITLE
Updated docker-compose.yml with CATALINA_OPTS

### ISSUE THREAD

**Issue by Limraj** [SCADA-LTS/Scada-LTS#2132]
**Target**
1. Among other things, it allows you to set parameters InitialHeapSize and MaxHeapSize, and other options for JVM;
2. Change master on latest tag;

**Comment by kinsamanka** [comment]
You can also add [wait-for-it.sh](https://github.com/vishnubob/wait-for-it) so that `scadalts` will start only once the database is ready to accept connections:

```
    scadalts:
        image: scadalts/scadalts:latest
        environment:
            - CATALINA_OPTS=-Xmx512m -Xms512m
        ports: 
            - "8080:8080"
        depends_on: 
            - database
        expose: ["8080", "8000"]
        links:
            - database:database
        command:
          - /usr/bin/wait-for-it.sh
          - --host=database
          - --port=3306
          - --timeout=30
          - --strict
          - --
          - /usr/local/tomcat/bin/catalina.sh
          - run
```
